apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: backend-pod
  template:
    metadata:
      labels:
        name: backend-pod
    spec:
      containers:
      - name: backend
        image: backend 
        # 這邊image需要先傳送給k8s的docker daemon
        imagePullPolicy: Never
        ports:
        - containerPort: 5000