apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    name: backend-service
spec:
  #type: ClusterIP
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30001
  selector:
    name: backend-pod


